keybindings:
  back: q
  next_page: ctrl-d
  previous_page: ctrl-u
  jump_to_start: g
  jump_to_end: G
  jump_to_album: a
  jump_to_artist_album: A
  jump_to_context: o
  manage_devices: m
  decrease_volume: '-'
  increase_volume: =
  toggle_playback: space
  seek_backwards: H
  seek_forwards: L
  next_track: n
  previous_track: N
  help: '?'
  shuffle: s
  repeat: r
  search: /
  submit: enter
  copy_song_url: y
  copy_album_url: Y
  audio_analysis: v
  basic_view: B
  add_item_to_queue: p
  open_settings: ','
  save_settings: ','
behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  volume_percent: 70
  tick_rate_milliseconds: 15
  enable_text_emphasis: true
  show_loading_indicator: true
  enforce_wide_search_bar: true
  enable_global_song_count: true
  enable_discord_rpc: true
  discord_rpc_client_id: null
  shuffle_enabled: true
  liked_icon: 
  shuffle_icon: 
  repeat_track_icon: 
  repeat_context_icon: 
  playing_icon: 
  paused_icon: 
  set_window_title: true
  visualizer_style: Equalizer
theme:
  active: 122, 162, 247
  banner: 187, 154, 247
  error_border: 247, 118, 142
  error_text: 247, 118, 142
  hint: 238, 207, 102
  hovered: 122, 162, 247
  inactive: 86, 95, 137
  playbar_background: 26, 27, 38
  playbar_progress: 158, 206, 106
  playbar_progress_text: 192, 202, 245
  playbar_text: 192, 202, 245
  selected: 122, 162, 247
  text: 192, 202, 245
  background: 26, 27, 38
  header: 125, 207, 255
  highlighted_lyrics: 158, 206, 106
